name: PowerfulAccountLock
version: 0.0.1
api: 4.0.0
main: YTBJero\PowerfulAccountLock\PowerfulAccountLock
website: https://github.com/EricGamingYT
load: STARTUP
description: Powerful Account Lock Plugin For PocketMine-MP
extensions:
  core: ">=8.0"